# Generated by Django 3.0.6 on 2020-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='post',
            field=models.CharField(max_length=750),
        ),
    ]
