# Generated by Django 3.0.6 on 2020-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostposts', '0002_auto_20200515_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='post',
            field=models.CharField(max_length=280),
        ),
    ]
