# Generated by Django 3.0.6 on 2020-06-18 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostposts', '0004_auto_20200617_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
